import React from 'react';
import { 
  ShieldCheck, 
  FileText, 
  Cpu, 
  History, 
  Lock, 
  Server, 
  AlertTriangle, 
  UserX, 
  RefreshCw, 
  Mail, 
  ArrowLeft,
  CheckCircle2,
  XCircle
} from 'lucide-react';

export default function PrivacyPolicy({ onNavigate }) {
  const lastUpdatedDate = "September 15, 2026";

  const sections = [
    {
      id: "what-is-trustcheck",
      number: "01",
      icon: ShieldCheck,
      title: "1. What TrustCheck Is",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            <strong className="text-white">TrustCheck</strong> is an educational scam and suspicious-message risk analysis tool designed to help users recognize threat patterns, social engineering tactics, and potential phishing markers in digital communications.
          </p>
          <p>
            TrustCheck provides automated risk assessments generated by heuristic analysis engines and artificial intelligence models. <strong className="text-cyber-accent">TrustCheck does not guarantee that a message, link, or attachment is completely safe or malicious.</strong> It is strictly an educational risk indicator and should not replace independent verification or professional security judgment.
          </p>
        </div>
      )
    },
    {
      id: "information-provided",
      number: "02",
      icon: FileText,
      title: "2. Information Users May Provide",
      content: (
        <div className="space-y-4 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            When utilizing the TrustCheck platform, you may provide or submit the following categories of information:
          </p>
          <ul className="space-y-2 text-slate-300">
            <li className="flex items-start gap-2.5">
              <span className="w-1.5 h-1.5 rounded-full bg-cyber-secondary mt-2 shrink-0" />
              <span><strong className="text-white">Analysis Submissions:</strong> Text content, email bodies, SMS messages, URL links, or text extracted from screenshots submitted into the scanner for evaluation.</span>
            </li>
            <li className="flex items-start gap-2.5">
              <span className="w-1.5 h-1.5 rounded-full bg-cyber-secondary mt-2 shrink-0" />
              <span><strong className="text-white">Account Information:</strong> Email address, user credentials, and profile identifiers created when registering an account.</span>
            </li>
            <li className="flex items-start gap-2.5">
              <span className="w-1.5 h-1.5 rounded-full bg-cyber-secondary mt-2 shrink-0" />
              <span><strong className="text-white">Scan History Data:</strong> Evaluation scores, risk breakdown metrics, threat tags, and timestamps tied to an authenticated account.</span>
            </li>
          </ul>
        </div>
      )
    },
    {
      id: "message-processing",
      number: "03",
      icon: Cpu,
      title: "3. How Submitted Messages Are Processed",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            Submitted messages and link snippets are processed by TrustCheck's automated threat detection systems and configured artificial intelligence providers to calculate risk scores, extract threat indicators, and provide safety recommendations.
          </p>
          <div className="p-4 rounded-xl bg-slate-900/80 border border-cyber-border/80 text-slate-300 text-xs sm:text-sm">
            <p className="font-semibold text-white mb-1">AI Provider Processing Notice:</p>
            <p>
              Submitted text content may be transmitted to and processed by configured third-party AI service providers (such as Google Gemini or Groq) in real time to generate risk reports. We do not claim that submitted messages are never processed by third-party AI services.
            </p>
          </div>
        </div>
      )
    },
    {
      id: "scan-history",
      number: "04",
      icon: History,
      title: "4. Scan History & Account Storage",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-1">
            <div className="p-4 rounded-xl bg-slate-900/60 border border-cyber-border">
              <h4 className="font-semibold text-white text-sm mb-2 flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-cyber-success shrink-0" />
                Authenticated Users
              </h4>
              <p className="text-xs sm:text-sm text-slate-400">
                When signed in, your scan results and risk assessments are securely linked to your account history so you can review, filter, and track previous risk reports over time.
              </p>
            </div>
            <div className="p-4 rounded-xl bg-slate-900/60 border border-cyber-border">
              <h4 className="font-semibold text-white text-sm mb-2 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-cyber-secondary shrink-0" />
                Guest Scans
              </h4>
              <p className="text-xs sm:text-sm text-slate-400">
                Scans performed without logging in are processed transiently to generate the immediate evaluation result and are not associated with or saved under a user account.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: "security",
      number: "05",
      icon: Lock,
      title: "5. Security Safeguards",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            We deploy technical, organizational, and administrative safeguards designed to protect stored account data and scan records against unauthorized access, alteration, or disclosure.
          </p>
          <p>
            However, please note that <strong className="text-white">no method of transmission over the Internet or electronic storage is 100% secure.</strong> While we strive to use commercially acceptable means to protect user information, TrustCheck cannot guarantee absolute security against all potential cyber threats or unauthorized access.
          </p>
        </div>
      )
    },
    {
      id: "third-party-services",
      number: "06",
      icon: Server,
      title: "6. Third-Party Infrastructure & Services",
      content: (
        <div className="space-y-4 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            TrustCheck relies on established third-party technology infrastructure to operate authentication, data persistence, and intelligence processing:
          </p>
          <div className="space-y-3">
            <div className="p-3.5 rounded-lg bg-slate-900/50 border border-cyber-border/70 flex items-start gap-3">
              <div className="px-2.5 py-1 rounded bg-cyber-primary/20 text-cyber-accent text-xs font-mono font-bold shrink-0 mt-0.5">
                Supabase
              </div>
              <p className="text-xs sm:text-sm text-slate-300">
                Used for managing user account authentication, encrypted session handling, and database storage for registered account histories.
              </p>
            </div>
            <div className="p-3.5 rounded-lg bg-slate-900/50 border border-cyber-border/70 flex items-start gap-3">
              <div className="px-2.5 py-1 rounded bg-cyber-secondary/20 text-cyber-secondary text-xs font-mono font-bold shrink-0 mt-0.5">
                AI Providers
              </div>
              <p className="text-xs sm:text-sm text-slate-300">
                Configured third-party AI models (including Google Gemini and Groq) utilized to perform natural language threat classification and evaluation.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: "user-responsibility",
      number: "07",
      icon: AlertTriangle,
      title: "7. User Responsibility & Sensitive Data",
      content: (
        <div className="space-y-4 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            TrustCheck is designed exclusively for evaluating suspicious text and identifying scam patterns. Users are strictly responsible for maintaining privacy regarding their own confidential credentials.
          </p>
          
          {/* Danger Warning Box */}
          <div className="p-4 rounded-xl bg-red-950/20 border border-red-500/30 space-y-3">
            <div className="flex items-center gap-2 text-red-400 font-semibold text-sm">
              <XCircle className="w-5 h-5 shrink-0" />
              <span>DO NOT SUBMIT HIGHLY SENSITIVE INFORMATION:</span>
            </div>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-xs sm:text-sm text-red-200/90 pl-1">
              <li className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                Account passwords or PINs
              </li>
              <li className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                API keys or private tokens
              </li>
              <li className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                Bank credentials or card numbers
              </li>
              <li className="flex items-center gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-red-400" />
                2FA authentication codes / OTPs
              </li>
            </ul>
          </div>
        </div>
      )
    },
    {
      id: "childrens-privacy",
      number: "08",
      icon: UserX,
      title: "8. Children's Privacy",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            TrustCheck is not intended for or targeted at children under 13 years of age. We do not knowingly collect, request, or solicit personal information from anyone under the age of 13.
          </p>
          <p>
            If we learn that we have collected personal data from a child under 13 without verified parental consent, we will promptly remove that information from our servers.
          </p>
        </div>
      )
    },
    {
      id: "policy-changes",
      number: "09",
      icon: RefreshCw,
      title: "9. Changes to This Privacy Policy",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            We may update or revise this Privacy Policy periodically to reflect changes in our platform practices, technology stack, or legal obligations.
          </p>
          <p>
            When changes are made, the <strong className="text-white">"Last updated"</strong> date at the top of this policy will be revised accordingly. We encourage users to review this page regularly to remain informed about how we safeguard your data.
          </p>
        </div>
      )
    },
    {
      id: "contact-us",
      number: "10",
      icon: Mail,
      title: "10. Contact Us",
      content: (
        <div className="space-y-3 text-slate-300 leading-relaxed text-sm sm:text-base">
          <p>
            If you have questions, inquiries, or concerns regarding this Privacy Policy or TrustCheck's data handling practices, please reach out to the TrustCheck team through the contact methods provided on our website.
          </p>
        </div>
      )
    }
  ];

  const scrollToSection = (id) => {
    const el = document.getElementById(id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  };

  return (
    <div className="pt-28 pb-20 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto animate-fadeIn">
      {/* Back Button */}
      <div className="mb-8">
        <button
          onClick={() => onNavigate('landing')}
          className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors cursor-pointer group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          <span>Back to Home</span>
        </button>
      </div>

      {/* Header Banner */}
      <div className="glass-panel p-6 sm:p-10 rounded-2xl mb-10 border border-cyber-border/80 relative overflow-hidden">
        <div className="absolute top-0 right-0 -mt-8 -mr-8 w-48 h-48 bg-cyber-primary/10 rounded-full blur-3xl pointer-events-none" />
        
        <div className="relative z-10 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyber-primary/20 border border-cyber-secondary/40 text-cyber-accent text-xs font-semibold uppercase tracking-wider">
            <ShieldCheck className="w-3.5 h-3.5 text-cyber-secondary" />
            <span>TrustCheck Legal Notice</span>
          </div>

          <h1 className="font-display font-extrabold text-3xl sm:text-5xl text-white tracking-tight">
            Privacy Policy
          </h1>

          <div className="flex flex-wrap items-center gap-4 text-xs sm:text-sm text-slate-400 pt-1">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-md bg-slate-900/80 border border-cyber-border font-mono text-slate-300">
              <span className="w-2 h-2 rounded-full bg-cyber-secondary animate-pulse" />
              Last updated: {lastUpdatedDate}
            </span>
            <span>Educational Risk Analysis Platform</span>
          </div>

          <p className="text-sm sm:text-base text-slate-300 max-w-3xl leading-relaxed pt-2">
            This Privacy Policy outlines how TrustCheck handles information when you interact with our suspicious message risk analysis platform.
          </p>
        </div>
      </div>

      {/* Quick Jump Index */}
      <div className="mb-10 p-5 glass-panel rounded-xl border border-cyber-border/60">
        <h3 className="text-xs uppercase font-bold text-slate-400 tracking-wider mb-3">
          Quick Navigation
        </h3>
        <div className="flex flex-wrap gap-2">
          {sections.map((sec) => (
            <button
              key={sec.id}
              onClick={() => scrollToSection(sec.id)}
              className="text-xs font-medium px-3 py-1.5 rounded-lg bg-slate-900/70 border border-cyber-border/60 text-slate-300 hover:text-white hover:border-cyber-secondary/50 hover:bg-slate-800 transition-all cursor-pointer"
            >
              {sec.title}
            </button>
          ))}
        </div>
      </div>

      {/* Sections List */}
      <div className="space-y-6">
        {sections.map((sec) => {
          const IconComponent = sec.icon;
          return (
            <section 
              key={sec.id} 
              id={sec.id} 
              className="glass-panel p-6 sm:p-8 rounded-2xl border border-cyber-border/70 hover:border-cyber-border transition-colors scroll-mt-28"
            >
              <div className="flex items-start gap-4 mb-4">
                <div className="p-2.5 rounded-xl bg-cyber-primary/10 border border-cyber-secondary/30 text-cyber-secondary shrink-0 mt-0.5">
                  <IconComponent className="w-5 h-5 text-glow" />
                </div>
                <div className="flex-grow">
                  <span className="text-xs font-mono font-semibold text-cyber-secondary tracking-wider block mb-1">
                    SECTION {sec.number}
                  </span>
                  <h2 className="font-display font-bold text-xl sm:text-2xl text-white">
                    {sec.title.replace(/^[0-9]+\.\s*/, '')}
                  </h2>
                </div>
              </div>

              <div className="pt-2">
                {sec.content}
              </div>
            </section>
          );
        })}
      </div>

      {/* Footer Navigation CTA */}
      <div className="mt-12 glass-panel p-8 rounded-2xl border border-cyber-border text-center space-y-4">
        <h3 className="font-display font-bold text-xl text-white">
          Ready to evaluate a suspicious message?
        </h3>
        <p className="text-sm text-slate-400 max-w-xl mx-auto">
          Scan suspicious texts, emails, and link indicators with automated threat assessment.
        </p>
        <div className="pt-2 flex justify-center gap-4">
          <button
            onClick={() => onNavigate('scanner')}
            className="px-6 py-2.5 rounded-lg text-sm font-semibold text-white bg-cyber-primary hover:bg-blue-500 shadow-[0_0_15px_-3px_rgba(37,99,235,0.4)] transition-all cursor-pointer"
          >
            Run Scanner Analysis
          </button>
          <button
            onClick={() => onNavigate('landing')}
            className="px-6 py-2.5 rounded-lg text-sm font-semibold text-slate-300 hover:text-white bg-slate-900 border border-cyber-border transition-all cursor-pointer"
          >
            Return to Home
          </button>
        </div>
      </div>
    </div>
  );
}
